
project:
  type: website
  output-dir: docs
  resources:
    - libs/
    - Week-2.html

website:
  title: "Learning Diary"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: week1.qmd
        text: Week 1
      - href: week2.qmd
        text: Week 2
      - href: week3.qmd
        text: Week 3
      - href: week4.qmd
        text: Week 4
